[[binds]]
proto = "http"
#type = "tcp"
#addr = "127.0.0.1"
type = "unix"
addr = "sock"

[[binds]]
proto = "dbus"
#type = "system"
type = "session"

[buttons.power]
chip = "gpiochip0"
line = 23

[buttons.reset]
chip = "gpiochip0"
line = 24

[leds.power]
chip = "gpiochip0"
line = 22

[leds.disk]
chip = "gpiochip0"
line = 27

[hid]
keybard = "hidg0"
mouse = "hidg1"

[video]
device = "video0"
